import {
  SiJavascript,
  SiPython,
  SiPhp,
  SiReact,
  SiAngular,
  SiBattledotnet,
  SiLaravel,
  SiDjango,
  SiSwift,
  SiKotlin,
  SiFlutter,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiGooglecloud,
  SiTypescript,
  SiApachecordova,
  SiNodedotjs,
  SiFigma,
  SiSketch,
  SiHtml5,
  SiCss3,
  SiFirebase,
  SiGooglesearchconsole,
  SiGoogleads,
  SiMeta,
  SiGoogle,
} from "react-icons/si";
import { FaAws, FaJava } from "react-icons/fa";
import { VscAzure } from "react-icons/vsc";
import { DiMsqlServer } from "react-icons/di";
import { PiFileCSharp } from "react-icons/pi";
import { GrIntegration } from "react-icons/gr";
import {
  FiSearch,
  FiTrendingUp,
  FiTarget,
  FiRepeat,
  FiEdit3,
  FiFileText,
  FiLayout,
  FiBookOpen,
  FiShare2,
  FiBarChart2,
  FiPieChart,
  FiActivity,
} from "react-icons/fi";

export const IconMap = {
  JavaScript: SiJavascript,
  Python: SiPython,
  "C#": PiFileCSharp,
  PHP: SiPhp,
  React: SiReact,
  Angular: SiAngular,
  ".NET": SiBattledotnet,
  Laravel: SiLaravel,
  Django: SiDjango,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  Flutter: SiFlutter,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  "SQL Server": DiMsqlServer,
  AWS: FaAws,
  Azure: VscAzure,
  "Google Cloud": SiGooglecloud,
  Java: FaJava,
  TypeScript: SiTypescript,
  AngularJS: SiAngular,
  Cordova: SiApachecordova,
  "ASP.Net": SiBattledotnet,
  "Node.js": SiNodedotjs,
  Figma: SiFigma,
  Sketch: SiSketch,
  HTML: SiHtml5,
  CSS: SiCss3,
  Firebase: SiFirebase,
  "Third-party integrations": GrIntegration,
  SEO: FiSearch,
  "Google Search": SiGooglesearchconsole,
  "Google Business Profile": SiGoogle,
  "Structured Data Optimisation": FiTrendingUp,
  "Paid Media": FiTarget,
  "Google Ads": SiGoogleads,
  "Meta Ads": SiMeta,
  "Retargeting Workflows": FiRepeat,
  Content: FiEdit3,
  "Service Pages": FiFileText,
  "Landing Pages": FiLayout,
  "Blog Strategy": FiBookOpen,
  Social: FiShare2,
  "Paid Social Campaign Execution": FiTarget,
  "Organic Social Campaign Execution": FiTrendingUp,
  Analytics: FiBarChart2,
  "Conversion Tracking": FiActivity,
  "Performance Dashboards": FiPieChart,
  "Periodic Strategy Reviews": FiTrendingUp,
};
